import { Vocabulary } from './types';

// Sample data with added examples
export const VOCABULARY_LIST: Vocabulary[] = [
  { id: 1, kanji: '身内', kana: 'みうち', meaningEn: 'relative', meaningKo: '친척, 집안 사람', example: '身内に医者がいると、何かと安心だ。' },
  { id: 2, kanji: '肉親', kana: 'にくしん', meaningEn: 'immediate family', meaningKo: '육친', example: '肉親を亡くす悲しみは計り知れない。' },
  { id: 3, kanji: '配偶者', kana: 'はいぐうしゃ', meaningEn: 'spouse', meaningKo: '배우자', example: '配偶者の有無を記入してください。' },
  { id: 4, kanji: '家系', kana: 'かけい', meaningEn: 'family line', meaningKo: '가계, 집안 내력', example: '彼は音楽家の家系に生まれた。' },
  { id: 5, kanji: 'おふくろ', kana: 'おふくろ', meaningEn: 'mom', meaningKo: '어머니 (친근한 표현)', example: 'おふくろの味が一番だ。' },
  { id: 6, kanji: 'おやじ', kana: 'おやじ', meaningEn: 'dad', meaningKo: '아버지 (친근한 표현)', example: 'うちのおやじは頑固だ。' },
  { id: 7, kanji: 'よこす', kana: 'よこす', meaningEn: 'send', meaningKo: '보내다, 넘겨주다', example: '手紙をよこす。' },
  { id: 8, kanji: '女房', kana: 'にょうぼう', meaningEn: 'wife', meaningKo: '마누라, 처', example: '女房に頭が上がらない。' },
  { id: 9, kanji: '亭主', kana: 'ていしゅ', meaningEn: 'husband', meaningKo: '남편', example: '亭主関白な家庭。' },
  { id: 10, kanji: '温もり', kana: 'ぬくもり', meaningEn: 'warmth', meaningKo: '온기, 따스함', example: '人の温もりが恋しい。' },
  { id: 11, kanji: '授かる', kana: 'さずかる', meaningEn: 'be given', meaningKo: '내려 주시다, (아이를) 갖게 되다', example: '子宝を授かる。' },
  { id: 12, kanji: '名付ける', kana: 'なづける', meaningEn: 'name', meaningKo: '이름 짓다', example: '新種の花に名前を名付ける。' },
  { id: 13, kanji: 'すやすや', kana: 'すやすや', meaningEn: 'sleep soundly', meaningKo: '새근새근', example: '赤ちゃんがすやすや眠っている。' },
  { id: 14, kanji: 'しぐさ', kana: 'しぐさ', meaningEn: 'gesture', meaningKo: '행동, 몸짓', example: '彼女の髪をかきあげるしぐさが好きだ。' },
  { id: 15, kanji: '愛しい', kana: 'いとしい', meaningEn: 'adorable', meaningKo: '사랑스럽다', example: '愛しい我が子。' },
  { id: 16, kanji: '懐く', kana: 'なつく', meaningEn: 'be attached', meaningKo: '따르다', example: '野良猫が私に懐いた。' },
  { id: 17, kanji: 'ねだる', kana: 'ねだる', meaningEn: 'scrounge', meaningKo: '조르다', example: 'お小遣いをねだる。' },
  { id: 18, kanji: 'すねる', kana: 'すねる', meaningEn: 'sulk', meaningKo: '토라지다, 삐치다', example: '子供がすねて口を利かない。' },
  { id: 19, kanji: '指図', kana: 'さしず', meaningEn: 'order', meaningKo: '지시', example: 'あれこれ指図されるのは嫌だ。' },
  { id: 20, kanji: '横取り', kana: 'よこどり', meaningEn: 'snatching', meaningKo: '가로챔', example: '人の手柄を横取りする。' },
  { id: 21, kanji: '反発', kana: 'はんぱつ', meaningEn: 'rebound, repel', meaningKo: '반발', example: '親に反発して家を出た。' },
  { id: 22, kanji: '家出', kana: 'いえで', meaningEn: 'running away from home', meaningKo: '가출', example: '家出少女を保護する。' },
  { id: 23, kanji: 'ぎくしゃく', kana: 'ぎくしゃく', meaningEn: 'be strained', meaningKo: '어색함', example: '彼との関係がぎくしゃくしている。' },
  { id: 24, kanji: '言い返す', kana: 'いいかえす', meaningEn: 'talk back', meaningKo: '말대꾸하다', example: '上司に言い返す勇気はない。' },
  { id: 25, kanji: '言い張る', kana: 'いいはる', meaningEn: 'insist', meaningKo: '우기다', example: '自分が正しいと言い張る。' },
  { id: 26, kanji: '門限', kana: 'もんげん', meaningEn: 'curfew', meaningKo: '통금 시간', example: '我が家の門限は10時だ。' },
  { id: 27, kanji: 'さんざん', kana: 'さんざん', meaningEn: 'severe, harsh', meaningKo: '몹시, 호되게', example: 'さんざん文句を言われた。' },
  { id: 28, kanji: '省みる', kana: 'かえりみる', meaningEn: 'reflect', meaningKo: '돌이켜보다', example: '自分の行いを省みる。' },
  { id: 29, kanji: 'さも', kana: 'さも', meaningEn: 'as if', meaningKo: '마치', example: 'さも知っているかのように話す。' },
  { id: 30, kanji: 'やまやまな', kana: 'やまやまな', meaningEn: 'have a strong desire', meaningKo: '간절한', example: '行きたいのはやまやまだが、時間がない。' },
  { id: 31, kanji: '再婚', kana: 'さいこん', meaningEn: 'remarry', meaningKo: '재혼', example: '母が再婚することになった。' },
  { id: 32, kanji: '健在な', kana: 'けんざいな', meaningEn: 'in good health', meaningKo: '건재함', example: '祖父はまだ健在だ。' },
  { id: 33, kanji: 'いたわる', kana: 'いたわる', meaningEn: 'care', meaningKo: '위로하다', example: '老人をいたわる。' },
  { id: 34, kanji: '他界', kana: 'たかい', meaningEn: 'pass away', meaningKo: '타계 (사망)', example: '父は先月他界しました。' },
  { id: 35, kanji: '受け継ぐ', kana: 'うけつぐ', meaningEn: 'take over', meaningKo: '이어받다', example: '伝統を受け継ぐ。' },
  { id: 36, kanji: '遺産', kana: 'いさん', meaningEn: 'inheritance', meaningKo: '유산', example: '遺産をめぐる争い。' },
  { id: 37, kanji: 'かけがえのない', kana: 'かけがえのない', meaningEn: 'invaluable', meaningKo: '둘도 없는', example: 'かけがえのない友人。' },
  { id: 38, kanji: '気が置けない', kana: 'きがおけない', meaningEn: 'easy to get along with', meaningKo: '허물없다', example: '気が置けない仲間たち。' },
  { id: 39, kanji: '気心', kana: 'きごころ', meaningEn: 'disposition', meaningKo: '기질, 성미', example: '気心の知れた仲。' },
  { id: 40, kanji: '打ち明ける', kana: 'うちあける', meaningEn: 'confess', meaningKo: '털어놓다', example: '秘密を打ち明ける。' },
  { id: 41, kanji: '察する', kana: 'さっする', meaningEn: 'sense', meaningKo: '헤아리다', example: '気配を察する。' },
  { id: 42, kanji: '同い年', kana: 'おないどし', meaningEn: 'same age', meaningKo: '동갑', example: '私たちは同い年だ。' },
  { id: 43, kanji: '連中', kana: 'れんちゅう', meaningEn: 'group', meaningKo: '녀석들', example: '怪しい連中がたむろしている。' },
  { id: 44, kanji: '呼び捨て', kana: 'よびすて', meaningEn: 'calling someone without honorifics', meaningKo: '경칭 생략', example: '年上を呼び捨てにするのは失礼だ。' },
  { id: 45, kanji: '身の上', kana: 'みのうえ', meaningEn: 'circumstances', meaningKo: '신세', example: '身の上相談に乗る。' },
  { id: 46, kanji: '徹する', kana: 'てっする', meaningEn: 'devote oneself to', meaningKo: '투철하다', example: '裏方に徹する。' },
  { id: 47, kanji: '踏みにじる', kana: 'ふみにじる', meaningEn: 'violate', meaningKo: '짓밟다', example: '人の思いを踏みにじる。' },
  { id: 48, kanji: '気に障る', kana: 'きにさわる', meaningEn: 'annoying', meaningKo: '비위에 거슬리다', example: '彼の態度は気に障る。' },
  { id: 49, kanji: 'きまり(が)悪い', kana: 'きまり(が)わるい', meaningEn: 'feel embarrassed', meaningKo: '쑥스럽다', example: '会議に遅れてきまりが悪かった。' },
  { id: 50, kanji: 'たかが', kana: 'たかが', meaningEn: 'only', meaningKo: '고작', example: 'たかが100円、されど100円。' }
];
